let mapleader = ","
filetype plugin indent on
nnoremap Y y$
set noshowmode
set mouse=a
syntax on
set term=screen-256color
set number
set relativenumber
set hidden
set backspace=indent,eol,start
set hls is " highlight matches and start search while typing
set showcmd " show incomplete commands in the status bar
set history=100
set autoindent "indents using whitespaces
set laststatus=2 " make file status etc. always visible
set cursorline
set smartindent
set ignorecase
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set scrolloff=8
set expandtab
set t_Co=256
set clipboard^=unnamed
set listchars=tab:▸\ ,trail:•,extends:❯,precedes:❮
set showbreak=↪\
set splitbelow splitright
set guioptions=

" use rg for grepping
set grepprg=rg\ --vimgrep\ --fixed-strings

" colorschemes!
set bg=dark
colorscheme gruvbox

nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
nnoremap j gj
nnoremap k gk

nnoremap <leader>> <C-W>>
nnoremap <leader>< <C-W><

"remove hanging whitespace
nnoremap <leader>s :%s/\s\+$//e<CR>

" open a new vertical split window with <leader> w
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <leader>v :vnew<CR>

"insert a timestamp in default date format
nnoremap <leader>dt :put =strftime('%c')<CR>

"nerdTREE
" toggle NerdTree with ctrl + n
map <C-n> :NERDTreeToggle<CR>
" quit vim if NerdTree is the only buffer
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" TeX Suite
let g:tex_flavor='latex'
let g:Tex_MultipleCompileFormats='dvi,pdf'

" GitGutter
let g:gitgutter_enabled = 0
let g:gitgutter_map_keys = 0
nnoremap <Leader>gg :GitGutterToggle<Cr>
nnoremap <Leader>gs :Gstatus<Cr>
nnoremap <Leader>gd :Gdiff<Cr>

autocmd Filetype gitcommit setlocal spell textwidth=72  " set columns to 72 on git commits

autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

" Simple re-format for minified Javascript
command! UnMinify call UnMinify()
function! UnMinify()
    %s/{\ze[^\r\n]/{\r/g
    %s/){/) {/g
    %s/};\?\ze[^\r\n]/\0\r/g
    %s/;\ze[^\r\n]/;\r/g
    %s/[^\s]\zs[=&|]\+\ze[^\s]/ \0 /g
    normal ggVG=
endfunction

" plugins
call plug#begin('~/.vim/plugged')
Plug 'Raimondi/delimitMate'
Plug 'airblade/vim-gitgutter'
Plug 'benmills/vimux'
Plug 'bling/vim-airline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'godlygeek/tabular'
Plug 'jlanzarotta/bufexplorer'
Plug 'junegunn/vim-slash'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'w0rp/ale'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()

" commentary
autocmd FileType matlab setlocal commentstring=\%\ %s

"ale
let g:ale_fix_on_save = 1
let g:ale_open_list = 1

let g:ale_linters = { 'python': ['flake8'], 'rust': ['rls'], 'javascript': ['eslint'] }
let g:ale_fixers = {
\   'rust': ['rustfmt'],
\   'python': ['black'],
\   'javascript': ['eslint', 'prettier'],
\   '*': ['remove_trailing_lines'],
\}
let g:ale_rust_rls_toolchain = 'stable'
let g:ale_python_flake8_options = '--max-line-length=88'

noremap <silent> H :ALEHover<CR>
noremap <silent> R :ALEFindReferences<CR>
noremap <silent> Q :ALEGoToDefinition<CR>

"vimux
 " Prompt for a command to run
 map <Leader>tr :VimuxPromptCommand<CR>
 " Run last command executed by VimuxRunCommand
 map <Leader>tt :VimuxRunLastCommand<CR>
" TabNine
set rtp+=~/tools/tabnine-vim
"fzf
set rtp+=/usr/local/opt/fzf
nnoremap <c-p> :Files<CR>
