general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock && openrgb --profile sleep 
    after_sleep_cmd = hyprctl dispatch dpms on && sleep 1 && hyprctl keyword device:all enabled true && openrgb --profile wake
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 5400
    on-timeout = systemctl suspend
}
